[package]
name = "music_card_catalog"
version = "0.1.0"
authors = ["Matt Bilker <me@mbilker.us>"]

[dependencies]
chromaprint	= "~0.1.2"
clap		= "~2.27.0"
dotenv		= "~0.10.1"
ffmpeg		= { git = "https://github.com/meh/rust-ffmpeg.git" }
log		= "~0.3.8"
mediainfo	= "~0.1.3"
postgres	= "~0.15"
rayon		= "~0.8.2"
serde		= "~1.0.15"
serde_derive	= "~1.0.15"
serde_yaml	= "~0.7.1"
walkdir		= "~1.0.7"
