[package]
name = "music_card_catalog"
version = "0.1.0"
authors = ["Matt Bilker <me@mbilker.us>"]

[dependencies]
clap		= "~2.26.2"
mediainfo	= "~0.1.3"
rayon		= "~0.8.2"
serde		= "~1.0.15"
serde_derive	= "~1.0.15"
serde_yaml	= "~0.7.1"
walkdir		= "~1.0.7"
